server:
  port: 8090

spring:
  ##数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mychat?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

  ##redis配置
  redis:
    host: 192.168.88.130
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        time-between-eviction-runs: 3000

    ##rabbitmq配置
  rabbitmq:
    host: 192.168.88.130
    port: 5672
    username: admin
    password: 123456

socketio:
  host: localhost
  port: 9092
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 10000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

gpt:
  model:
    key: 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
proxy:
   host: 127.0.0.1
   port: 7890